#! /bin/bash

ignore_dirs="lm_resolve1 regex_noimports sg_lib"


for d in */ ; do

    d=${d::-1}

    if echo $ignore_dirs | grep -q "$d" ; then
      continue
    fi

    echo "[?] Compiling grammar $d..."

    out=$(bash -c "./$d/compile" 2>&1)
    exit=$?

    if [ "$exit" -eq "0" ]; then
      echo "[✔] LM compiler for grammar $d successfully built, executing ./$d/clean"
      ./"$d"/clean
    else
      echo "[✗] Something went wrong when building the LM compiler for grammar $d"
      echo -e -n "$out\n"
      break
    fi

done