#!/bin/bash

sed -i 's/globalScope_value.setParent(this);/globalScope_value.setParent(this);\n    this.setChild(globalScope_value, 1);/g' AST/Program.java

sed -i 's/modScope_value.setParent(this);/modScope_value.setParent(this);\n    this.setChild(modScope_value, 1);/g' AST/ModuleDecl.java

sed -i 's/varScope_value.setParent(this);/varScope_value.setParent(this);\n    this.setChild(varScope_value, 2);/g' AST/ParBind.java

sed -i 's/r_value.setParent(this);/r_value.setParent(this);\n    this.setChild(r_value, 0);/g' AST/ModRef.java

sed -i 's/r_value.setParent(this);/r_value.setParent(this);\n    this.setChild(r_value, 0);/g' AST/VarRef.java

sed -i 's/dfa_value.setParent(this);/dfa_value.setParent(this);\n    this.setChild(dfa_value, 0);/g' AST/MkVarRef.java

sed -i 's/dfa_value.setParent(this);/dfa_value.setParent(this);\n    this.setChild(dfa_value, 0);/g' AST/MkModRef.java

sed -i 's/sinkState_value.setParent(this);/sinkState_value.setParent(this);\n    this.setChild(sinkState_value, 0);/g' AST/DFA.java

sed -i 's/finalState_value.setParent(this);/finalState_value.setParent(this);\n    this.setChild(finalState_value, 1);/g' AST/DFA.java

sed -i 's/lexState_value.setParent(this);/lexState_value.setParent(this);\n    this.setChild(lexState_value, 2);/g' AST/ModDFA.java

sed -i 's/impState_value.setParent(this);/impState_value.setParent(this);\n    this.setChild(impState_value, 3);/g' AST/ModDFA.java

sed -i 's/lexState_value.setParent(this);/lexState_value.setParent(this);\n    this.setChild(lexState_value, 2);/g' AST/VarDFA.java

sed -i 's/impState_value.setParent(this);/impState_value.setParent(this);\n    this.setChild(impState_value, 3);/g' AST/VarDFA.java