#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo "load-and-test: Expected two argument, a Statix specification in our 
          language, and a directory to look for test case programs."
    exit 0
fi

TSTS=$2
TSTS="${TSTS%/}"

# build the translator if not present

if [ ! -f statix_translate.driver.jar ]; then
    echo "Building translator..."
    statix_translate/compile  &> /dev/null 2>&1;
fi

# translate the spec

java -jar statix_translate.driver.jar $1

mv statix-spec.mstx ministatix/src
mv ocaml_ag_lm_spec.ml ocaml_lib
mv *.sv silverstuff/statix_trans

./alltests $TSTS

# cleanup

rm -f *.jar *.mstx *.sv *.ml
rm ministatix/src/statix-spec.mstx
rm ocaml_lib/ocaml_ag_lm_spec.ml
rm silverstuff/statix_trans/Spec_*.sv