#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

cp $1/Main.sv silverstuff/statix_trans

cd silverstuff

./compile > /dev/null 2>&1

OUT=$(java -jar statix_trans.jar 2>&1)

rm statix_trans.jar

./clean

cd ..

if [[ $OUT == *"outer.ok = true"* ]]; then
  echo -e "- ${GREEN}Satisfiable${NC} by Silver AG"
elif [[ $OUT == *"outer.ok = false"* ]]; then
  echo -e "- ${RED}Unsatisfiable${NC} by Silver AG"
elif [[ $OUT == *"Cycle detected"* ]]; then
  echo -e "- ${YELLOW}Cycle${NC} detected Silver AG"
fi