#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ocamlbuild $1/ag_test.byte -I lib/ocaml_lib &> /dev/null

OUT=$(ocamlrun ag_test.byte 2>&1)

if [[ $OUT == *"outer.ok = true"* ]]; then
  echo -e "- ${GREEN}Satisfiable${NC} by OCaml AG"
  exit 0
elif [[ $OUT == *"outer.ok = false"* ]]; then
  echo -e "- ${RED}Unsatisfiable${NC} by OCaml AG (outer.ok == false)"
  exit 1
elif [[ $OUT == *"aborting"* ]]; then
  echo -e "- ${RED}Unsatisfiable${NC} by OCaml AG (evaluation aborted)"
  exit 1
elif [[ $OUT == *"Cycle detected"* ]]; then
  echo -e "- ${YELLOW}Cycle${NC} detected OCaml AG"
  exit 2
fi

rm ag_test.byte
rm -r _build