#!/bin/bash

# expects first argument to be a path to a directory containing an ocaml test case program called `ag_test.ml`
# e.g. ./ocamltest testcases/module_simple

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if [[ $# -ne 1 ]] ; then
    echo "try-one-input: Expected one argument, the path of a directory containing a 
          test case 'mstx.aterm'."
    exit 0
fi

bash test-mstx $1
MSTX_RES=$?
bash test-ocaml $1
OCAML_RES=$?
bash test-silver $1
SILVER_RES=$?

if [ $MSTX_RES -eq $OCAML_RES -a $MSTX_RES -eq $SILVER_RES ]; then
    echo -e "- ${GREEN}Success${NC} - Test results are matching."
    exit 0
else
    echo -e "- ${RED}Failure${NC} - Test results are not matching."
    exit 1
fi