#!/bin/bash

orig=$DIR

if [ -d ../ministatix.hs ]; then
  echo "[✗] Ministatix directory already exists, see ../ministatix.hs"
  exit 0
fi

if git clone https://github.com/metaborg/ministatix.hs.git; then
  echo "[✔] Ministatix successfully cloned"
else
  echo "[✗] Something went wrong when cloning Ministatix"
  exit -1
fi

mv ministatix.hs ..
cd ../ministatix.hs

if make build; then
  echo "[✔] Ministatix successfully built at ../ministatix.hs"
else
  echo "[✗] Something went wrong when building Ministatix"
fi

cd ../$orig
