#!/bin/bash

# run all test cases, based on dirs in testcases/

if [[ $# -ne 1 ]] ; then
    echo "alltests: Expected one argument, a directory to look for test case 
          programs."
    exit 0
fi

for testcase in $1/*/ ; do
    bash onetest $testcase
done