#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

OUT=$(ministatix.hs/statix check -I ministatix.hs/src statix-spec $1/mstx.aterm)

if [[ $OUT == *"Satisfiable"* ]]; then
  echo -e "- ${GREEN}Satisfiable${NC} by Ministatix"
elif [[ $OUT == *"Unsatisfiable"* ]]; then
  echo -e "- ${RED}Unsatisfiable${NC} by Ministatix"
elif [[ $OUT == *"Stuck"* ]]; then
  echo -e "- ${YELLOW}Stuck${NC} in Ministatix"
fi

rm .statix