#!/bin/bash

# setting up ministatix

echo "[!] Building Minstatix..."

make -C ministatix.hs

# setting up AG translator - for now just compiling from ../statix_translate

echo "[!] Building Translator..."

bash ../statix_translate/compile

echo "[!] Done building!"